import './routes/get-dishes.js'
import './routes/add-dish.js'
import './routes/edit-dish.js'
import './routes/get-image.js'
import './routes/delete-dish.js'
import './routes/dish-of-the-day.js'
import './routes/rate-dish.js'